version: "3.8"

services:
  mysql:
    user: "${UID}:${GID}" 
    image: mysql:latest
    container_name: mysqldatabase
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myDB
      MYSQL_USER: rahul
      MYSQL_PASSWORD: mysecurepass
    volumes:
      - /Users/rahulsingh/Documents/volumes/todo_volume:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql  
    networks:
      - data_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  todo_app:
    image: notorious007/python_todo_app:latest
    container_name: todo_app
    ports:
      - "1000:1000"
    environment:
      MYSQL_HOST: mysqldatabase
      MYSQL_USER: rahul
      MYSQL_PASSWORD: mysecurepass
      MYSQL_DB: myDB
    depends_on:
      - mysqldatabase
    networks:
      - data_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  data_network:
