services:
  mysql:
    image: mysql:latest
    container_name: mysqldatabase
    environment:
      MYSQL_ROOT_PASSWORD:  rootpass 
      MYSQL_DATABASE: myDB
      MYSQL_USER: rahul
      MYSQL_PASSWORD: mysecurepass
    volumes:
      - /Users/rahulsingh/Documents/volumes/todo_volume:/var/lib/mysql
    networks:
      - data_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-uroot","-prootpsass"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  todo_app:
    image: notorious007/python_todo_app:latest
    container_name: todo_app
    environment:
      MYSQL_HOST: mysqldatabase
      MYSQL_USER: rahul
      MYSQL_PASSWORD: mysecurepass
      MYSQL_DB: myDB
    networks:
      - data_network
    ports:
      - "1000:1000"
    depends_on:
      - mysql


volumes: {}

networks:
  data_network:
  
